[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "torchaudio_filters"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["torchaudio"]

[project.optional-dependencies]
dev = ["scipy", "pytest"]
