[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "torchaudio_filters"
version = "0.0.1"
dependencies = ["torchaudio"]

[project.optional-dependencies]
dev = ["pytest", "scipy"]

